--CREATE DATABASE bnb-db;--

CREATE TABLE ROOMS
  (ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  WEEKEND_RATE DECIMAL,
  WEEKDAY_RATE DECIMAL);

CREATE TABLE GUEST
  (ID INT PRIMARY KEY,
  FIRSTNAME VARCHAR(255),
  LASTNAME VARCHAR(255),
  PHONE_NUMBER VARCHAR(255),
  CREDIT_CARD_NUMBER VARCHAR(255),
  CREDIT_CARD_EXPIRATION VARCHAR(255),
  RESERVATION_ID, INT);

CREATE TABLE RESERVATION
  (ID INT PRIMARY KEY,
  ROOM_ID INT,
  START_DATE DATE,
  END_DATE DATE,
  BOOKED_DATED DATE,
  BALANCE_DUE_DATE DATE,
  BALANCE DECIMAL,
  CANCELED SMALLINT);

